### PR TITLE
Nomenclature update

### PR DESCRIPTION
**Pull request by bradeales**
Renamed "SCU" and "DEU" to "Preselector" and "Receiver" respectively. Removed "Version #" text; this will be designated by release/tagged version.

### CODE REVIEW

**Review by djanderson — APPROVED** [review]
This looks good and improves the readability of the affected sections 10-fold.

**Comment by MichaelCotton** [comment]
Agreed - much better. 

A couple questions for consistency:
1. In Preselector table, should {name in first column}/{Object name in description} be rf_path_specs/RFPathSpecs or rf_path/RFPath? 
2. In SteppedFrequencyFFTDetection table, should the name in the fourth row be single_frequency_fft_detection?

**Comment by bradeales** [comment]
To me it would be a lot cleaner dropping the 'specs' portion from the name, especially since we don't use 'specs' in any of our other objects.

Yep, agreed, 'SingleFrequencyFFTDetection' should be 'single_frequency_fft_detection' in name.

**Review by MichaelCotton — APPROVED** [review]
Looks good.

**Comment by djanderson** [comment]
Actually it should probably be `rf_paths` that replaces `rf_path_specs` because it's an array of RFPath objects, and that' the convention that we've been using.

**Pull request merged**
